name: memelusion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Firebase Core
  firebase_core: ^2.25.4

  # ✅ Firebase Authentication
  firebase_auth: ^4.17.4

  # ✅ Firestore for Database
  cloud_firestore: ^4.15.4
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1


  # ✅ State management if needed (optional)
  provider: ^6.1.2
  http: ^1.2.1
  firebase_storage: ^11.7.1
  uuid: ^4.3.3
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and add asset paths if you use local images/fonts
  assets:
    - assets/img/background.jpg
    - assets/img/default_profile.png
  #   - assets/memes/
