// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWRMV0AAdDdsxxeGTSOV_FVOWFQimrp6U',
    appId: '1:562977872383:web:0229520ec5e4270154efca',
    messagingSenderId: '562977872383',
    projectId: 'memelusion-9303b',
    authDomain: 'memelusion-9303b.firebaseapp.com',
    storageBucket: 'memelusion-9303b.firebasestorage.app',
    measurementId: 'G-E6XMF6V5CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8jx40ljI8krjelIiErc7LLe-EGm8vIUE',
    appId: '1:562977872383:android:5243a32c4b0bcf1a54efca',
    messagingSenderId: '562977872383',
    projectId: 'memelusion-9303b',
    storageBucket: 'memelusion-9303b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-2u4rRHvxJ9S-GfioslPQQcUeJ9NBJJM',
    appId: '1:562977872383:ios:73dab05618d10c3b54efca',
    messagingSenderId: '562977872383',
    projectId: 'memelusion-9303b',
    storageBucket: 'memelusion-9303b.firebasestorage.app',
    iosBundleId: 'com.example.memelusion',
  );
}
